name: StellerPark
favicon: null
layout_spectrum: 0.6013710934203118
typography_spectrum: 0.9786848293151706
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.650749770924449
  lightness: 0.27372640767134726
  saturation: 0.7237231442704797
  rhythmicContrast: 0.4128170011099428
purpose: []
