typography_spectrum: 0.9786848293151706
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.650749770924449
  lightness: 0.27372640767134726
  saturation: 0.7237231442704797
  rhythmicContrast: 0.4128170011099428
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6013710934203118
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/67f3967a-338d-4634-a85d-83d67b9ce1a3.png
name: Steller Park
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f8b9beb8-bfaf-41d4-ad18-9dc6961e0ed3.png
title: The Creative Company
purpose: []
